-- SPDX-License-Identifier: MIT
with MC_Types; use MC_Types; with MC_Time_Guard; with MC_Retry_Budget;
with MC_Health_Report; with MC_SHA256; with MC_Site_Policy; with MC_Witness;
with Test_Support; use Test_Support;
procedure Run_Resilience_Contract_Tests with SPARK_Mode=>Off is
   use type Byte; use type MC_Retry_Budget.State; use type MC_Health_Report.Report;
   P : MC_Retry_Budget.Policy; S,Before : MC_Retry_Budget.State;
   Report_Value,Parsed : MC_Health_Report.Report; Data : MC_Health_Report.Frame;
   Stamp : MC_Time_Guard.Stamp; Status : Outcome;
   Policy,Decoded : MC_Site_Policy.Policy;
begin
   Stamp:=((others=>1),1,100,200);
   Expect(MC_Time_Guard.Fresh(Stamp,(others=>1),150,100),"fresh-inclusive-start");
   Expect(not MC_Time_Guard.Fresh(Stamp,(others=>1),200,100),"expiry-exclusive");
   Expect(not MC_Time_Guard.Fresh(Stamp,(others=>2),150,100),"boot-scoped-time");
   Expect(not MC_Time_Guard.Fresh(Stamp,(others=>1),99,100),"future-observation-denied");
   Expect(MC_Time_Guard.Add_Bounded(Counter'Last-1,3)=Counter'Last,"saturating-time");
   S.Boot_ID:=(others=>1); Before:=S;
   MC_Retry_Budget.Reserve(S,P,(others=>2),0,Status); Expect(Status=Stale and then S=Before,"wrong-boot-no-charge");
   MC_Retry_Budget.Reserve(S,P,(others=>1),0,Status); Expect(Status=OK and then S.Total=1,"first-charge");
   Before:=S; MC_Retry_Budget.Reserve(S,P,(others=>1),1,Status);
   Expect(Status=Denied and then S=Before,"backoff-preserves-state");
   MC_Retry_Budget.Reserve(S,P,(others=>1),5_000,Status); Expect(Status=OK and then S.Total=2,"second-charge");
   MC_Retry_Budget.Reserve(S,P,(others=>1),15_000,Status); Expect(Status=OK and then S.Count=3,"third-charge");
   Before:=S; MC_Retry_Budget.Reserve(S,P,(others=>1),35_000,Status);
   Expect(Status=Denied and then S=Before,"window-limit-is-cooldown-not-reset");
   MC_Retry_Budget.Rebind_Boot(S,P,(others=>2),10,Status);
   Expect(Status=OK and then S.Total=3 and then S.Count=3 and then S.Consecutive=3,"reboot-preserves-debt");
   Expect(S.Attempts(1)=10 and then S.Attempts(3)=10 and then S.Not_Before=300_010,"reboot-conservative-clock");
   Before:=S; MC_Retry_Budget.Reserve(S,P,(others=>2),11,Status);
   Expect(Status=Denied and then S=Before,"no-reboot-budget-bypass");
   MC_Retry_Budget.Confirm_Stable(S,12,Status);
   Expect(Status=OK and then S.Total=3 and then S.Count=3 and then S.Consecutive=0,"stable-only-clears-consecutive");
   MC_Retry_Budget.Reserve(S,P,(others=>2),3_600_010,Status);
   Expect(Status=OK and then S.Total=4 and then S.Count=1,"window-expiry-does-not-erase-lifetime");
   P.Maximum_Total:=4; Before:=S;
   MC_Retry_Budget.Reserve(S,P,(others=>2),4_000_000,Status);
   Expect(Status=Exhausted and then S=Before,"lifetime-exhaustion-latches");
   P.Maximum_Total:=100; Before:=S;
   MC_Retry_Budget.Reserve(S,P,(others=>2),Counter'Last,Status);
   Expect(Status=Exhausted and then S=Before,"deadline-overflow-denied");
   for I in 0..200 loop Expect(MC_Retry_Budget.Backoff(P,I)<=P.Maximum_Backoff_Ms,"backoff-bounded"); end loop;
   Report_Value.Cluster_ID:=(others=>1); Report_Value.Node_ID:=(others=>2); Report_Value.Resource_ID:=(others=>3);
   Report_Value.Invocation_ID:=(others=>4); Report_Value.Configuration:=(others=>5); Report_Value.Recovery_Policy:=(others=>6);
   Report_Value.Stamp:=((others=>7),8,9,19); Report_Value.Result:=MC_Health_Report.Healthy;
   Report_Value.Config_Valid:=True; Report_Value.Dependencies_Ready:=True; Report_Value.Data_Compatible:=True;
   Report_Value.Ownership_Exclusive:=True; Report_Value.Business_Healthy:=True;
   Data:=MC_Health_Report.Encode(Report_Value); MC_Health_Report.Decode(Data,Parsed,Status);
   Expect(Status=OK and then Parsed=Report_Value,"health-report-roundtrip");
   for I in Data'Range loop
      Data(I):=Data(I) xor 1; MC_Health_Report.Decode(Data,Parsed,Status);
      Expect(Status/=OK,"every-byte-corruption-rejected"); Data(I):=Data(I) xor 1;
   end loop;
   Data(185):=1; Data(225..256):=MC_SHA256.Hash(Data(1..224)); MC_Health_Report.Decode(Data,Parsed,Status);
   Expect(Status/=OK,"reserved-byte-even-with-new-checksum");
   Data:=MC_Health_Report.Encode(Report_Value); Data(177):=255; Data(225..256):=MC_SHA256.Hash(Data(1..224));
   MC_Health_Report.Decode(Data,Parsed,Status); Expect(Status/=OK,"unknown-condition-denied");
   Data:=MC_Health_Report.Encode(Report_Value); Data(178):=2; Data(225..256):=MC_SHA256.Hash(Data(1..224));
   MC_Health_Report.Decode(Data,Parsed,Status); Expect(Status/=OK,"noncanonical-boolean");
   Policy.Root_ID:=(others=>1); Policy.Scope.Resource_ID:=Policy.Root_ID;
   Policy.Scope.Cluster_ID:=(others=>2); Policy.Scope.Node_ID:=(others=>3);
   Policy.Scope.Membership_Epoch:=1; Policy.Scope.Fence_Token:=1; Policy.Request_Key:=(others=>4);
   Policy.Contract:=(others=>5); Policy.Serial:=1; Policy.Valid_Until:=100;
   for K in MC_Witness.Fact loop Policy.Observers(K):=(others=>Byte(10+MC_Witness.Fact'Pos(K))); end loop;
   MC_Site_Policy.Decode(MC_Site_Policy.Encode(Policy),Decoded,Status); Expect(Status=OK,"independent-observer-policy");
   for K in MC_Witness.Fact loop
      Policy.Observers(K):=Policy.Request_Key; MC_Site_Policy.Decode(MC_Site_Policy.Encode(Policy),Decoded,Status);
      Expect(Status/=OK,"requester-cannot-attest-own-facts"); Policy.Observers(K):=(others=>Byte(10+MC_Witness.Fact'Pos(K)));
   end loop;
   Report;
end Run_Resilience_Contract_Tests;
