#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate independent component CI/test runners from the shared test plan."""
from pathlib import Path
import argparse
import json
import shlex
import engineering as eng

ROOT = Path(__file__).resolve().parents[2]


def generated():
    tests = eng.load_json(ROOT/'assurance/engineering/test-plan.json')['ada_tests']
    packages = (ROOT/'dev/packages.txt').read_text().split()
    for repo in eng.REPOS:
        lines = ['#!/bin/sh', '# SPDX-License-Identifier: MIT',
                 '# Generated by assurance/ci/sync-component-ci.py; edit test-plan.json.',
                 'set -eu', 'umask 077',
                 'cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"',
                 '[ "$(id -u)" -ne 0 ] || { echo "Use an unprivileged build user" >&2; exit 78; }',
                 'D=$(mktemp -d "${TMPDIR:-/tmp}/nia-tests.XXXXXXXX")',
                 'trap \'rm -rf -- "$D"\' EXIT HUP INT TERM']
        if repo == 'pkgcore':
            lines.append('python3 "$PWD/tests/make_deb_final_set_fixtures.py" --check')
            lines.append('python3 "$PWD/tests/make_deb_transition_fixtures.py" --check')
        for test in tests:
            if not test['main'].startswith(repo+'/'):
                continue
            name = Path(test['main']).stem
            def arg(value):
                if value.startswith('$TEMP/'):
                    return '"$D/"'+shlex.quote(name+'/'+value[6:])
                return '"$PWD/"'+shlex.quote(value)
            lines.append('mkdir -p "$D/'+name+'"')
            for directory in test['prepare_directories']:
                lines.append('mkdir -p '+arg(directory))
            lines.append('echo '+shlex.quote('Running '+name))
            command = ('timeout --kill-after=5s 600s env -i PATH="$PATH" HOME="$D" TMPDIR="$D" LANG=C.UTF-8 LC_ALL=C.UTF-8 '+
                       '"$PWD/build/test-bin/'+name+'"'+ ''.join(' '+arg(value) for value in test['arguments']))
            if repo == 'pkgcore' and name == 'run_deb_final_set_tests':
                lines.extend(['if '+command+' > "$D/final-set-native.log" 2>&1; then',
                              '  cat "$D/final-set-native.log"', 'else',
                              '  cat "$D/final-set-native.log"', '  exit 1', 'fi',
                              'python3 "$PWD/tests/compare_deb_final_set.py" --media "$PWD/tests/fixtures/deb-final-set" --native "$D/final-set-native.log" --output "$D/final-set-native-oracle.json"'])
            elif repo == 'pkgcore' and name == 'run_deb_transition_tests':
                lines.extend(['if '+command+' > "$D/transition-native.log" 2>&1; then',
                              '  cat "$D/transition-native.log"', 'else',
                              '  cat "$D/transition-native.log"', '  exit 1', 'fi',
                              'python3 "$PWD/tests/compare_deb_transition.py" --media "$PWD/tests/fixtures/deb-transition" --native "$D/transition-native.log" --output "$D/transition-native-oracle.json"'])
            elif repo == 'pkgcore' and name == 'run_catalog_store_tests':
                lines.extend(['if '+command+' > "$D/catalog-store-native.log" 2>&1; then',
                              '  cat "$D/catalog-store-native.log"', 'else',
                              '  cat "$D/catalog-store-native.log"', '  exit 1', 'fi',
                              'python3 "$PWD/tests/compare_catalog_store.py" --media "$PWD/tests/fixtures/selected-catalog" --native "$D/catalog-store-native.log" --cas "$D/run_catalog_store_tests/store" --output "$D/catalog-store-oracle.json"'])
            else:
                lines.append(command)
        if repo == 'pkgcore':
            lines.append('timeout --kill-after=5s 600s python3 "$PWD/tests/check_deb_final_set_upstream.py" --media "$PWD/tests/fixtures/deb-final-set" --work "$D/upstream-endpoint"')
        yield ROOT/repo/'ci/test-all.sh', ('\n'.join(lines)+'\n').encode(), 0o755
        for name in ('gnatprove.lock.json','install-gnatprove.py','proof-guard.py'):
            if repo != 'assurance':
                yield ROOT/repo/'ci'/name,(ROOT/'assurance/ci'/name).read_bytes(),0o644
        proof = '''# SPDX-License-Identifier: MIT
# Generated by assurance/ci/sync-component-ci.py.
# All component proofs share the guard's per-user lock. No unbounded fallback.
.PHONY: flow prove
flow: check-contract
\t@command -v "$(GNATPROVE)" >/dev/null || { echo 'GNATprove missing; proof NOT RUN' >&2; exit 78; }
\tmkdir -p build/proof-obj
\tpython3 ci/proof-guard.py -- "$(GNATPROVE)" -P proof.gpr -U --mode=flow --checks-as-errors=on --warnings=error
prove: check-contract
\t@command -v "$(GNATPROVE)" >/dev/null || { echo 'GNATprove missing; proof NOT RUN' >&2; exit 78; }
\tmkdir -p build/proof-obj
\tpython3 ci/proof-guard.py -- "$(GNATPROVE)" -P proof.gpr -U --mode=all --level=4 --checks-as-errors=on --warnings=error --proof-warnings=on --report=statistics
'''
        yield ROOT/repo/'ci/proof.mk',proof.encode(),0o644
        setup = '''#!/bin/sh
# SPDX-License-Identifier: MIT
# Generated component CI dependency setup; use only in the pinned CI container.
set -eu
[ "$(id -u)" -eq 0 ] || exit 78
rm -f /etc/apt/sources.list.d/debian.sources
cat > /etc/apt/sources.list <<'SOURCES'
deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20260907T000000Z trixie main
deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20260907T000000Z trixie-updates main
deb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/20260907T000000Z trixie-security main
SOURCES
apt-get update
apt-get install -y --no-install-recommends ''' + ' '.join(packages) + '\n'
        yield ROOT/repo/'ci/setup-container.sh',setup.encode(),0o755
        workflow = '''# Generated by assurance/ci/sync-component-ci.py.
name: Component validation
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  native:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    container:
      image: debian:13.6-slim@sha256:abc9cb88a5587630d7f915f47b23b0668fe250fbfc6457aa4d52b534c1bbf73f
      options: --memory=3g --memory-swap=3g --cpus=1 --pids-limit=128
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Install pinned development dependencies
        run: sh ci/setup-container.sh
      - name: Prepare unprivileged builder
        run: |
          useradd --create-home builder
          chown -R builder:builder "$GITHUB_WORKSPACE"
      - name: Compile, link and run every Ada test
        run: runuser -u builder -- make compile-all build test
  proof:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    container:
      image: debian:13.6-slim@sha256:abc9cb88a5587630d7f915f47b23b0668fe250fbfc6457aa4d52b534c1bbf73f
      options: --memory=3g --memory-swap=3g --cpus=1 --pids-limit=128
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - run: sh ci/setup-container.sh
      - run: |
          useradd --create-home builder
          chown -R builder:builder "$GITHUB_WORKSPACE"
      - name: Install checksum-pinned prover and check SPARK
        run: |
          runuser -u builder -- sh -ec '
            prover_bin=$(python3 ci/install-gnatprove.py)
            export PATH="$prover_bin:$PATH"
            make flow prove JOBS=1
          '
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: spark-results
          path: build/proof-obj/gnatprove/
'''
        if repo == 'pkgcore':
            workflow = workflow.replace('  proof:\n',
                '      - name: Verify generation, payload, catalog and endpoint root refusal\n'
                '        run: sh ci/generation-root-refusal-test.sh\n'
                '  proof:\n', 1)
        yield ROOT/repo/'.github/workflows/ci.yml',workflow.encode(),0o644


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    args=parser.parse_args()
    eng.validate(ROOT)
    failed=[]
    for path,data,mode in generated():
        if args.write:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(data);path.chmod(mode)
        elif not path.is_file() or path.read_bytes()!=data or path.stat().st_mode & 0o777 != mode:
            failed.append(str(path.relative_to(ROOT)))
    if failed:raise SystemExit('Generated CI differs: '+', '.join(failed))
    print('Component CI and all registered test runners match the canonical plan.')


if __name__=='__main__':main()
